### ISSUE TITLE
Documentation recommends utilising internal-use functions

### ISSUE THREAD

**Issue by phil-s** [dalanicolai/image-roll.el#1]
> The core functionality, i.e. the ‘scroll’ is provided by the `image-roll--new-window-function` and `image-roll--redisplay` functions.

With the double-hyphen naming, these are implicitly internal-use functions, per coding conventions.  As such, it's unexpected that the documentation recommends that people utilise them directly:

> The function `image-roll--new-window-function` should be added to the `image-mode-new-window-functions` while the `image-roll--redisplay` should be added to the `window-configuration-change-hook` both as buffer local hook functions

These should be renamed, yes?  If the above is intended to be a reliable public API, there shouldn't be any double-hyphens names involved.

**Comment by dalanicolai** [comment]
This is a good point. Thanks for pointing this out. I have corrected the names.
