### ISSUE TITLE
Symbol’s function definition is void: image-roll--new-window-function

### ISSUE THREAD

**Issue by stewmehr** [dalanicolai/image-roll.el#2]
I've tried to install via `straight` (and `use-package`) using the following config in `Emacs 29.0.50`:

```lisp
  (use-package pdf-tools
    :straight
    (:host github
     :repo "dalanicolai/pdf-tools"
     :branch "pdf-roll"
     :files ("lisp/*.el"
             "README"
             ("build" "Makefile")
             ("build" "server")
             (:exclude "lisp/tablist.el" "lisp/tablist-filter.el")))
  ...)

  (use-package image-roll
    :straight
    (:host github :repo "dalanicolai/image-roll.el"))
```

No issues with downloading and building but when I run `M-x pdf-view-roll-minor-mode` in a PDF buffer, I get

```
pdf-view-roll-minor-mode: Symbol’s function definition is void: image-roll--new-window-function
redisplay_internal (C function): Symbol’s function definition is void: image-roll--redisplay
pdf-view-next-line-or-next-page: Wrong type argument: overlayp, nil
```

in the `*Messages*` buffer. Is it possible that some of the macros are not expanded correctly, adding an additional `-` between package name and function suffix?

**Comment by dalanicolai** [comment]
Oh, that is very sloppy. I guess this has to do with the renaming I applied
today, to correctly follow Emacs conventions (see this issue
<https://github.com/dalanicolai/image-roll.el/issues/1>).
But of course I had to update the pdf-tools and doc-view parts also. I did
that now. Please try again.

Thank you for creating the issue!

**Comment by stewmehr** [comment]
Haha, I saw that there was one closed issue, glanced at the title, and thought: "nah, some coding recommendation probably has nothing to do with my problem". Should have kept reading ...

I still get the error

```
pdf-view-redisplay: Symbol’s function definition is void: image-roll--redisplay
```

but for the first time ever, I have continuous PDF scrolling in Emacs! 😍

**Comment by dalanicolai** [comment]
Yeah, I still forgot to rename one function, I hoped you had not tried it yet. I guess this last error should be fixed now also. If not then please let me know. Anyway, thanks for trying the package and enjoy! (I hope you are aware that there is still some issue when jumping forrward a single page while the next page is already visible. But I hope that gets fixed soon).

**Comment by stewmehr** [comment]
Scrolling works like a charm now, thank you :) I only have a minor issue with page numbers not being displayed, but that one probably deserves its own issue. Will close this one for now.
